services:
  bilibili-cookie-mgmt:
    image: ghcr.io/jkfujr/bilibilicookiemgmt:latest
    container_name: bilibili-cookie-mgmt
    ports:
      - "18000:18000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
